- name: datagrid-services-apb playbook to unbind the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: unbind-datagrid-services-apb
    playbook_debug: false
